version: "3.9"
name: uptime-webhook
services:
  webhook:
    container_name: uptime-webhook
    image: hatamiarash7/uptime-webhook:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./configs/config.yml
        target: /app/configs/config.yml
        bind:
          create_host_path: true
networks:
  default:
    name: uptime-webhook_default
